language: python
python:
  - "2.7"
env:
  - DJANGO_VERSION=1.5.1 DB=postgres
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r requirements.txt --use-mirrors
script:
  - python manage.py test
