language: python
python:
  - "2.7"
services:
  - elasticsearch
  - memcached
  - rabbitmq
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - pip install -r requirements.txt --use-mirrors
  - pip install coveralls --use-mirrors
  - npm install -g less
before_script:
  - psql -c 'DROP DATABASE IF EXISTS dezede;' -U postgres
  - psql -c 'CREATE DATABASE dezede;' -U postgres
script:
  - coverage run --source=dezede,libretto,accounts,dossiers,typography,cache_tools manage.py test
after_success:
  - coveralls
