language: python
python:
  - "2.7"
  - "pypy"
env:
  - DJANGO_VERSION=1.5.1
install:
  - pip install -q Django==$DJANGO_VERSION --use-mirrors
  - pip install -r requirements.txt --use-mirrors
  - sh -c "if [ `python -c 'import sys; print(\"__pypy__\" in sys.builtin_module_names)'` = 'True' ]; then pip install -r requirements_pypy.txt; else pip install -r requirements_py.txt; fi"
  - pip install coveralls --use-mirrors
before_script:
  - psql -c 'DROP DATABASE IF EXISTS dezede;' -U postgres
  - psql -c 'CREATE DATABASE dezede;' -U postgres
script:
  - coverage run --source=dezede,libretto,accounts,dossiers,typography,cache_tools manage.py test
after_success:
  - coveralls
