language: python
python:
  - "2.7"
env:
  - DJANGO_VERSION=1.5.1
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r requirements.txt --use-mirrors
before_script:
  - psql -c 'DROP DATABASE IF EXISTS dezede;' -U postgres
  - psql -c 'create database dezede;' -U postgres
script:
  - python manage.py test
