language: python
python:
  - 2.7
services:
  - elasticsearch
  - redis-server
before_install:
  # Starts Redis in a socket file.
  - sudo sh -c "echo 'unixsocket /var/run/redis/redis.sock\nunixsocketperm 777' >> /etc/redis/redis.conf"
  - sudo service redis-server restart
  # Starts a virtual desktop for Selenium tests.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - pip install -r requirements.txt --use-mirrors
  - npm install -g less
  - pip install coveralls --use-mirrors
before_script:
  - psql -c 'DROP DATABASE IF EXISTS dezede;' -U postgres
  - psql -c 'CREATE EXTENSION postgis;' -U postgres
  - psql -c 'CREATE USER dezede SUPERUSER;' -U postgres
  - psql -c 'CREATE DATABASE dezede OWNER dezede;' -U postgres
  - psql -c 'CREATE EXTENSION postgis;' -U postgres dezede
script:
  - coverage run --source=dezede,libretto,accounts,dossiers,typography,cache_tools manage.py test
after_success:
  - coveralls
