language: python
python:
  - "2.7"
services:
  - elasticsearch
  - rabbitmq
before_install:
  # Starts Redis in a socket file.
  - sudo sh -c "echo 'unixsocket /var/run/redis/redis.sock\nunixsocketperm 777' >> /etc/redis/redis.conf"
  - sudo service redis-server restart
  # Starts a virtual desktop for Selenium tests.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - pip install -r requirements.txt --use-mirrors
  - npm install -g less
  - pip install coveralls --use-mirrors
before_script:
  - psql -c 'DROP DATABASE IF EXISTS dezede;' -U postgres
  - psql -c 'CREATE USER dezede LOGIN;' -U postgres
  - psql -c 'CREATE DATABASE dezede OWNER dezede;' -U postgres
  # Starts a celery worker in the background and discards the output.
  - celery -A dezede worker </dev/null &>/dev/null &
script:
  - coverage run --source=dezede,libretto,accounts,dossiers,typography,cache_tools manage.py test
after_success:
  - coveralls
